- name: get pip
  dnf:
    name: python3-pip
    state: present

- name: get aws cli
  pip:
    name: awscli

- name: make aws config dir
  file:
    path: "/root/.aws"
    state: directory

- name: configure aws cli
  template:
    src: templates/awsconfig.j2
    dest: "/root/.aws/config"

- name: make sync dir if not exists
  file:
    path: "{{ s3_sync_source_location }}"
    state: directory

- name: create systemd S3 sync service unit and timer
  template:
    src: "{{ item }}"
    dest: "/etc/systemd/system/{{ item | splitext | first }}"
    owner: root
    group: root
    mode: 0644
  notify:
    - restart s3_sync
  loop:
    - s3_sync.service.j2
    - s3_sync.timer.j2
